spring.application.name=tntt_manager
spring.datasource.url=jdbc:postgresql://localhost:5432/tntt_manager
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# C?u hình Hibernate t? ??ng c?p nh?t c?u trúc b?ng t? Java Class xu?ng Postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect